# Generated by Django 3.1.5 on 2021-02-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
            ],
        ),
    ]
