# Generated by Django 3.1.5 on 2021-03-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightsOut', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={},
        ),
    ]
