# Generated by Django 3.1.7 on 2021-02-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightsOut', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='Loses',
            new_name='loses',
        ),
    ]
