# Generated by Django 2.2.17 on 2021-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsOut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Wins', models.IntegerField()),
                ('Loses', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
